### ISSUE TITLE
B站验证码获取失败

### ISSUE THREAD

**Issue by xiao-gy** [jackjieYYY/ArknightsHostingAgent#1]

**Comment by xiao-gy** [comment]
人在b服，但是获取不了验证码，没办法登录QAQ

**Comment by xiao-gy** [comment]
顺便反馈一个BUG，官服和b服用同一个手机号导致没办法同时托管，会冲突，希望能按照服务器分一下类型

**Comment by jackjieYYY** [comment]
> 顺便反馈一个BUG，官服和b服用同一个手机号导致没办法同时托管，会冲突，希望能按照服务器分一下类型

感谢您的反馈，目前项目正在重构，同时非常欢迎加群进行协助开发 450555868
